# Generated by Django 4.1.1 on 2022-09-18 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_comentcrm"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comentcrm",
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
    ]
